from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import io
import re

def generate_pdf_report(question, answer, confidence, opportunity_score, score_reasoning, sources):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=inch, leftMargin=inch,
                           topMargin=inch, bottomMargin=inch)

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=20,
        textColor=colors.HexColor('#1a56db'),
        spaceAfter=6
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#1a56db'),
        spaceBefore=12,
        spaceAfter=4
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#333333'),
        spaceAfter=6,
        leading=16
    )
    
    meta_style = ParagraphStyle(
        'Meta',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        spaceAfter=4
    )

    story = []

    story.append(Paragraph("Market Entry Analyzer", title_style))
    story.append(Paragraph("AI-Powered Market Intelligence Report", meta_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1a56db')))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Query", heading_style))
    story.append(Paragraph(question, body_style))
    story.append(Spacer(1, 8))

    score_color = '#22c55e' if opportunity_score >= 7 else '#eab308' if opportunity_score >= 5 else '#ef4444'
    story.append(Paragraph("Scores", heading_style))
    story.append(Paragraph(f"Confidence Score: {confidence}%", meta_style))
    story.append(Paragraph(f"Opportunity Score: {opportunity_score}/10", meta_style))
    story.append(Paragraph(f"Reasoning: {score_reasoning}", meta_style))
    story.append(Spacer(1, 8))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cccccc')))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Analysis", heading_style))
    
    clean_answer = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', answer)
    clean_answer = re.sub(r'\*(.*?)\*', r'<i>\1</i>', clean_answer)
    
    for line in clean_answer.split('\n'):
        line = line.strip()
        if line:
            if line.startswith('<b>') and line.endswith('</b>'):
                story.append(Paragraph(line, heading_style))
            elif line.startswith('- ') or line.startswith('* '):
                story.append(Paragraph(f"• {line[2:]}", body_style))
            else:
                story.append(Paragraph(line, body_style))

    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cccccc')))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Sources", heading_style))
    for i, source in enumerate(sources):
        story.append(Paragraph(f"{i+1}. {source}", meta_style))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by Market Entry Analyzer | Powered by Groq + ChromaDB", meta_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()